=== openflexo-team/openflexo-xml/xml-ta-test-rc/src/main/resources/TestResourceCenter/XSD/library.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
		targetNamespace="http://www.example.org/Library" 
		xmlns="http://www.example.org/Library"
		xmlns:tns="http://www.example.org/Library" 
		elementFormDefault="qualified">
		
<xs:element name="Library" type="LibraryType" />

  <xs:complexType name="LibraryType">
    <xs:sequence>
      <xs:element name="name" type="xs:string" />
      <xs:element maxOccurs="unbounded" minOccurs="0" name="Writer" type="Writer" />
      <xs:element maxOccurs="unbounded" minOccurs="0" name="Book" type="Book" />
    </xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="Book">
    <xs:sequence>
      <xs:element name="title" type="xs:string" />
      <xs:element name="pages" type="xs:int" />
      <xs:element name="category" type="BookCategory" />
      <xs:element name="author" type="xs:anyURI" />
    </xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="Writer">
    <xs:sequence>
      <xs:element name="name" type="xs:string" />
      <xs:element maxOccurs="unbounded" minOccurs="0" name="Book" type="xs:anyURI" />
    </xs:sequence>
  </xs:complexType>
  
  <xs:simpleType name="BookCategory">
    <xs:restriction base="xs:NCName">
      <xs:enumeration value="Mystery" />
      <xs:enumeration value="ScienceFiction" />
      <xs:enumeration value="Biography" />
    </xs:restriction>
  </xs:simpleType>

</xs:schema>

=== openflexo-team/openflexo-xml/xml-ta-test-rc/src/main/resources/TestResourceCenter/XML/example_library_1.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:Library 
	xmlns:p="http://www.example.org/Library" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://www.example.org/Library ../XSD/library.xsd ">
  <p:name><![CDATA[My Library]]></p:name>
  <p:Writer>
   <p:name>Hector</p:name>
   <p:Book>tutu</p:Book>
   <p:Book>tonton</p:Book> 
  </p:Writer>
  <p:Writer>
   <p:name>Simeon Le Papillon</p:name>
   <p:Book>tutu</p:Book>
   <p:Book>toto</p:Book> 
  </p:Writer>
  <p:Book>
   <p:title>toto</p:title>
   <p:pages>35</p:pages>
   <p:category>Mystery</p:category>
   <p:author>Le Lapin Rose des Alpes</p:author>
  </p:Book>
  <p:Book>
   <p:title>tutu</p:title>
   <p:pages>37</p:pages>
   <p:category>Biography</p:category>
   <p:author>La Poule</p:author>
  </p:Book>
</p:Library>
