=== openflexo-team/openflexo-xml/xml-ta-test-rc/src/main/resources/TestResourceCenter/CaoticWorkflow/OtawaPipeline.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
		targetNamespace="http://mem4csd.telecom-paris.fr/OtawaPipeline" 
		xmlns="http://mem4csd.telecom-paris.fr/OtawaPipeline"
		elementFormDefault="qualified">
  <xs:element name="name" type="xs:string"/>
  <xs:element name="width" type="xs:byte"/>
  <xs:element name="type" type="xs:string"/>
  <xs:element name="latency" type="xs:byte"/>
  <xs:element name="fu">
    <xs:complexType mixed="true">
      <xs:sequence>
        <xs:element ref="name" minOccurs="0"/>
        <xs:element ref="width" minOccurs="0"/>
        <xs:element ref="latency" minOccurs="0"/>
      </xs:sequence>
      <xs:attribute type="xs:string" name="id" use="optional"/>
      <xs:attribute type="xs:string" name="ref" use="optional"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="inst">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="type"/>
        <xs:element ref="fu"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="ordered" type="xs:boolean"/>
  <xs:element name="fus">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="fu" maxOccurs="unbounded" minOccurs="1"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="dispatch">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="inst"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="stage">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="name"/>
        <xs:element ref="width"/>
        <xs:element ref="type"/>
        <xs:element ref="ordered" minOccurs="0"/>
        <xs:element ref="fus" minOccurs="0"/>
        <xs:element ref="dispatch" minOccurs="0"/>
      </xs:sequence>
      <xs:attribute type="xs:string" name="id" use="optional"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="arch" type="xs:string"/>
  <xs:element name="model" type="xs:string"/>
  <xs:element name="stages">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="stage" maxOccurs="unbounded" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="processor">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="arch"/>
        <xs:element ref="model"/>
        <xs:element ref="stages"/>
      </xs:sequence>
      <xs:attribute type="xs:string" name="class"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== openflexo-team/openflexo-xml/xml-ta-test-rc/src/main/resources/TestResourceCenter/CaoticWorkflow/otawa_pipeline.xml
<?xml version="1.0" encoding="UTF-8"?>
<processor  
    xmlns="http://mem4csd.telecom-paris.fr/OtawaPipeline" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:schemaLocation="http://mem4csd.telecom-paris.fr/OtawaPipeline OtawaPipeline.xsd"
    class="otawa::hard::Processor">
	<arch>patmos</arch>
	<model>patmos</model>
	
	<stages>
		
		<stage id="FE">
			<name>FE</name>
			<width>2</width>
			<type>FETCH</type>
		</stage>

		<stage id="DE">
			<name>DE</name>
			<width>2</width>
			<type>LAZY</type>
		</stage>

		<stage id="EX">
			<name>EX</name>
			<width>2</width>
			<type>EXEC</type>
			<ordered>true</ordered>
			<fus>
				<fu id="ALU">
					<name>ALU</name>
					<width>2</width>
					<latency>1</latency>
				</fu>
			</fus>
			<dispatch>
				<inst>
					<type/>
					<fu ref="ALU"/>
				</inst>
			</dispatch>

		</stage>

		<stage id="MEM">
			<name>MEM</name>
			<width>2</width>
			<type>LAZY</type>
		</stage>

		<stage id="CM">
			<name>CM</name>
			<width>2</width>
			<type>COMMIT</type>
		</stage>
	</stages>

</processor>
